# Generated by Django 4.1.3 on 2022-11-14 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_content_contact_description_contact_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='semester',
            new_name='Class',
        ),
    ]
