# Generated by Django 4.1.3 on 2022-11-14 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_name_contact_full_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Student',
        ),
    ]
